package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WCertificore;
import com.umbrella.worker.entity.WCertificoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WCertificoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int countByExample(WCertificoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int deleteByExample(WCertificoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int insert(WCertificore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int insertSelective(WCertificore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    List<WCertificore> selectByExample(WCertificoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    WCertificore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") WCertificore record, @Param("example") WCertificoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByExample(@Param("record") WCertificore record, @Param("example") WCertificoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByPrimaryKeySelective(WCertificore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_certificore
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByPrimaryKey(WCertificore record);
}