package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WCoupon;
import com.umbrella.worker.entity.WCouponExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int countByExample(WCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int deleteByExample(WCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int insert(WCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int insertSelective(WCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    List<WCoupon> selectByExample(WCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    WCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") WCoupon record, @Param("example") WCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int updateByExample(@Param("record") WCoupon record, @Param("example") WCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int updateByPrimaryKeySelective(WCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_coupon
     *
     * @mbggenerated Thu Oct 20 03:40:41 CST 2016
     */
    int updateByPrimaryKey(WCoupon record);
}