package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WMemberDetail;
import com.umbrella.worker.entity.WMemberDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WMemberDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int countByExample(WMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int deleteByExample(WMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int insert(WMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int insertSelective(WMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    List<WMemberDetail> selectByExample(WMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    WMemberDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") WMemberDetail record, @Param("example") WMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int updateByExample(@Param("record") WMemberDetail record, @Param("example") WMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int updateByPrimaryKeySelective(WMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_member_detail
     *
     * @mbggenerated Thu Aug 04 15:08:41 CST 2016
     */
    int updateByPrimaryKey(WMemberDetail record);
}