package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WMembers;
import com.umbrella.worker.entity.WMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int countByExample(WMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int deleteByExample(WMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int insert(WMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int insertSelective(WMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    List<WMembers> selectByExample(WMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    WMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") WMembers record, @Param("example") WMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int updateByExample(@Param("record") WMembers record, @Param("example") WMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int updateByPrimaryKeySelective(WMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_members
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    int updateByPrimaryKey(WMembers record);
}