package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WMenu;
import com.umbrella.worker.entity.WMenuExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface WMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int countByExample(WMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int deleteByExample(WMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int insert(WMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int insertSelective(WMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    List<WMenu> selectByExample(WMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    WMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") WMenu record, @Param("example") WMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int updateByExample(@Param("record") WMenu record, @Param("example") WMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int updateByPrimaryKeySelective(WMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_menu
     *
     * @mbggenerated Sun Aug 07 17:15:37 CST 2016
     */
    int updateByPrimaryKey(WMenu record);
}