package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WOrderTask;
import com.umbrella.worker.entity.WOrderTaskExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WOrderTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int countByExample(WOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int deleteByExample(WOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int insert(WOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int insertSelective(WOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    List<WOrderTask> selectByExample(WOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    WOrderTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") WOrderTask record, @Param("example") WOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int updateByExample(@Param("record") WOrderTask record, @Param("example") WOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int updateByPrimaryKeySelective(WOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_order_task
     *
     * @mbggenerated Sun Aug 14 17:09:54 CST 2016
     */
    int updateByPrimaryKey(WOrderTask record);
}