package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WSmsRecord;
import com.umbrella.worker.entity.WSmsRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WSmsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int countByExample(WSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int deleteByExample(WSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int insert(WSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int insertSelective(WSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    List<WSmsRecord> selectByExample(WSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    WSmsRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") WSmsRecord record, @Param("example") WSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int updateByExample(@Param("record") WSmsRecord record, @Param("example") WSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int updateByPrimaryKeySelective(WSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_record
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    int updateByPrimaryKey(WSmsRecord record);
}