package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WSmsCode;
import com.umbrella.worker.entity.WSmsCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WSmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int countByExample(WSmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int deleteByExample(WSmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int insert(WSmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int insertSelective(WSmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    List<WSmsCode> selectByExample(WSmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    WSmsCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") WSmsCode record, @Param("example") WSmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int updateByExample(@Param("record") WSmsCode record, @Param("example") WSmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int updateByPrimaryKeySelective(WSmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sms_code
     *
     * @mbggenerated Fri Aug 05 11:25:33 CST 2016
     */
    int updateByPrimaryKey(WSmsCode record);
}