package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WStaffTime;
import com.umbrella.worker.entity.WStaffTimeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WStaffTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int countByExample(WStaffTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int deleteByExample(WStaffTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int insert(WStaffTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int insertSelective(WStaffTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    List<WStaffTime> selectByExample(WStaffTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    WStaffTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") WStaffTime record, @Param("example") WStaffTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int updateByExample(@Param("record") WStaffTime record, @Param("example") WStaffTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int updateByPrimaryKeySelective(WStaffTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    int updateByPrimaryKey(WStaffTime record);
}