package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WSupplierWorker;
import com.umbrella.worker.entity.WSupplierWorkerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WSupplierWorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int countByExample(WSupplierWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int deleteByExample(WSupplierWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int insert(WSupplierWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int insertSelective(WSupplierWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    List<WSupplierWorker> selectByExample(WSupplierWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    WSupplierWorker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") WSupplierWorker record, @Param("example") WSupplierWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int updateByExample(@Param("record") WSupplierWorker record, @Param("example") WSupplierWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int updateByPrimaryKeySelective(WSupplierWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier_worker
     *
     * @mbggenerated Fri Aug 12 13:52:58 CST 2016
     */
    int updateByPrimaryKey(WSupplierWorker record);
}