package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WTransaction;
import com.umbrella.worker.entity.WTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int countByExample(WTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int deleteByExample(WTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int insert(WTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int insertSelective(WTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    List<WTransaction> selectByExample(WTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    WTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") WTransaction record, @Param("example") WTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByExample(@Param("record") WTransaction record, @Param("example") WTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByPrimaryKeySelective(WTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_transaction
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    int updateByPrimaryKey(WTransaction record);
}