package com.umbrella.worker.dao;

import com.umbrella.worker.entity.WWorkerTask;
import com.umbrella.worker.entity.WWorkerTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WWorkerTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int countByExample(WWorkerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int deleteByExample(WWorkerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int insert(WWorkerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int insertSelective(WWorkerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    List<WWorkerTask> selectByExample(WWorkerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    WWorkerTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") WWorkerTask record, @Param("example") WWorkerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int updateByExample(@Param("record") WWorkerTask record, @Param("example") WWorkerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int updateByPrimaryKeySelective(WWorkerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_worker_task
     *
     * @mbggenerated Tue Aug 02 17:38:59 CST 2016
     */
    int updateByPrimaryKey(WWorkerTask record);
}