package com.umbrella.worker.entity;

import java.util.Date;

public class WAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.ID
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.W_ATTACH_NAME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private String wAttachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.W_ATTACH_PATH
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private String wAttachPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.W_ATTACH_URI
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private String wAttachUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.MODIFI_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private Date modifiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private String modifiAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.STATUS
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_attachment.DATALEVEL
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    private Integer datalevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.ID
     *
     * @return the value of w_attachment.ID
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.ID
     *
     * @param id the value for w_attachment.ID
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.W_ATTACH_NAME
     *
     * @return the value of w_attachment.W_ATTACH_NAME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public String getwAttachName() {
        return wAttachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.W_ATTACH_NAME
     *
     * @param wAttachName the value for w_attachment.W_ATTACH_NAME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setwAttachName(String wAttachName) {
        this.wAttachName = wAttachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.W_ATTACH_PATH
     *
     * @return the value of w_attachment.W_ATTACH_PATH
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public String getwAttachPath() {
        return wAttachPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.W_ATTACH_PATH
     *
     * @param wAttachPath the value for w_attachment.W_ATTACH_PATH
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setwAttachPath(String wAttachPath) {
        this.wAttachPath = wAttachPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.W_ATTACH_URI
     *
     * @return the value of w_attachment.W_ATTACH_URI
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public String getwAttachUri() {
        return wAttachUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.W_ATTACH_URI
     *
     * @param wAttachUri the value for w_attachment.W_ATTACH_URI
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setwAttachUri(String wAttachUri) {
        this.wAttachUri = wAttachUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.CREATE_TIME
     *
     * @return the value of w_attachment.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.CREATE_TIME
     *
     * @param createTime the value for w_attachment.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.MODIFI_TIME
     *
     * @return the value of w_attachment.MODIFI_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public Date getModifiTime() {
        return modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.MODIFI_TIME
     *
     * @param modifiTime the value for w_attachment.MODIFI_TIME
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setModifiTime(Date modifiTime) {
        this.modifiTime = modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.MODIFI_AUTHOR
     *
     * @return the value of w_attachment.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public String getModifiAuthor() {
        return modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.MODIFI_AUTHOR
     *
     * @param modifiAuthor the value for w_attachment.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setModifiAuthor(String modifiAuthor) {
        this.modifiAuthor = modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.STATUS
     *
     * @return the value of w_attachment.STATUS
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.STATUS
     *
     * @param status the value for w_attachment.STATUS
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_attachment.DATALEVEL
     *
     * @return the value of w_attachment.DATALEVEL
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_attachment.DATALEVEL
     *
     * @param datalevel the value for w_attachment.DATALEVEL
     *
     * @mbggenerated Fri Aug 26 17:24:04 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }
}