package com.umbrella.worker.entity;

import java.util.Date;

public class WCertificore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.W_CE_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wCeScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.W_CE_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wCeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.W_CE_ATTAC_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wCeAttacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.W_CE_VALID_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Date wCeValidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.CREATE_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.CREATE_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String createAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.MODIFI_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Date modifiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String modifiAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer datalevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_certificore.STATUS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.ID
     *
     * @return the value of w_certificore.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.ID
     *
     * @param id the value for w_certificore.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.W_CE_SCHEDULE_ID
     *
     * @return the value of w_certificore.W_CE_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwCeScheduleId() {
        return wCeScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.W_CE_SCHEDULE_ID
     *
     * @param wCeScheduleId the value for w_certificore.W_CE_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCeScheduleId(Integer wCeScheduleId) {
        this.wCeScheduleId = wCeScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.W_CE_NAME
     *
     * @return the value of w_certificore.W_CE_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwCeName() {
        return wCeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.W_CE_NAME
     *
     * @param wCeName the value for w_certificore.W_CE_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCeName(String wCeName) {
        this.wCeName = wCeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.W_CE_ATTAC_ID
     *
     * @return the value of w_certificore.W_CE_ATTAC_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwCeAttacId() {
        return wCeAttacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.W_CE_ATTAC_ID
     *
     * @param wCeAttacId the value for w_certificore.W_CE_ATTAC_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCeAttacId(Integer wCeAttacId) {
        this.wCeAttacId = wCeAttacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.W_CE_VALID_TIME
     *
     * @return the value of w_certificore.W_CE_VALID_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Date getwCeValidTime() {
        return wCeValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.W_CE_VALID_TIME
     *
     * @param wCeValidTime the value for w_certificore.W_CE_VALID_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCeValidTime(Date wCeValidTime) {
        this.wCeValidTime = wCeValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.CREATE_TIME
     *
     * @return the value of w_certificore.CREATE_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.CREATE_TIME
     *
     * @param createTime the value for w_certificore.CREATE_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.CREATE_AUTHOR
     *
     * @return the value of w_certificore.CREATE_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.CREATE_AUTHOR
     *
     * @param createAuthor the value for w_certificore.CREATE_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.MODIFI_TIME
     *
     * @return the value of w_certificore.MODIFI_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Date getModifiTime() {
        return modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.MODIFI_TIME
     *
     * @param modifiTime the value for w_certificore.MODIFI_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setModifiTime(Date modifiTime) {
        this.modifiTime = modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.MODIFI_AUTHOR
     *
     * @return the value of w_certificore.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getModifiAuthor() {
        return modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.MODIFI_AUTHOR
     *
     * @param modifiAuthor the value for w_certificore.MODIFI_AUTHOR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setModifiAuthor(String modifiAuthor) {
        this.modifiAuthor = modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.DATALEVEL
     *
     * @return the value of w_certificore.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.DATALEVEL
     *
     * @param datalevel the value for w_certificore.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_certificore.STATUS
     *
     * @return the value of w_certificore.STATUS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_certificore.STATUS
     *
     * @param status the value for w_certificore.STATUS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}