package com.umbrella.worker.entity;

public class WComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.W_MEMBERS_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wMembersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.W_STAFF_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.W_C_TITLE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wCTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.W_C_CONTENT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wCContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_comment.W_C_NICKNAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wCNickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.ID
     *
     * @return the value of w_comment.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.ID
     *
     * @param id the value for w_comment.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.W_MEMBERS_ID
     *
     * @return the value of w_comment.W_MEMBERS_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwMembersId() {
        return wMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.W_MEMBERS_ID
     *
     * @param wMembersId the value for w_comment.W_MEMBERS_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwMembersId(Integer wMembersId) {
        this.wMembersId = wMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.W_STAFF_ID
     *
     * @return the value of w_comment.W_STAFF_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwStaffId() {
        return wStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.W_STAFF_ID
     *
     * @param wStaffId the value for w_comment.W_STAFF_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwStaffId(Integer wStaffId) {
        this.wStaffId = wStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.W_C_TITLE
     *
     * @return the value of w_comment.W_C_TITLE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwCTitle() {
        return wCTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.W_C_TITLE
     *
     * @param wCTitle the value for w_comment.W_C_TITLE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCTitle(String wCTitle) {
        this.wCTitle = wCTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.W_C_CONTENT
     *
     * @return the value of w_comment.W_C_CONTENT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwCContent() {
        return wCContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.W_C_CONTENT
     *
     * @param wCContent the value for w_comment.W_C_CONTENT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCContent(String wCContent) {
        this.wCContent = wCContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_comment.W_C_NICKNAME
     *
     * @return the value of w_comment.W_C_NICKNAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwCNickname() {
        return wCNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_comment.W_C_NICKNAME
     *
     * @param wCNickname the value for w_comment.W_C_NICKNAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwCNickname(String wCNickname) {
        this.wCNickname = wCNickname;
    }
}