package com.umbrella.worker.entity;

import java.util.Date;

public class WOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wOScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_CONTACT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wOContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_CITY
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wOCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_DISTRICT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wODistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_TELEPHONE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wOTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_ADDRESS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wOAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_SUPPLIER_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private String wOSupplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_BEGIN_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Date wOBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_END_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Date wOEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_HOUR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wOHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.W_O_STAFF_COUNT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer wOStaffCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_order_detail.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    private Integer datalevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.ID
     *
     * @return the value of w_order_detail.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.ID
     *
     * @param id the value for w_order_detail.ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_SCHEDULE_ID
     *
     * @return the value of w_order_detail.W_O_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwOScheduleId() {
        return wOScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_SCHEDULE_ID
     *
     * @param wOScheduleId the value for w_order_detail.W_O_SCHEDULE_ID
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOScheduleId(Integer wOScheduleId) {
        this.wOScheduleId = wOScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_CONTACT
     *
     * @return the value of w_order_detail.W_O_CONTACT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwOContact() {
        return wOContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_CONTACT
     *
     * @param wOContact the value for w_order_detail.W_O_CONTACT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOContact(String wOContact) {
        this.wOContact = wOContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_CITY
     *
     * @return the value of w_order_detail.W_O_CITY
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwOCity() {
        return wOCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_CITY
     *
     * @param wOCity the value for w_order_detail.W_O_CITY
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOCity(String wOCity) {
        this.wOCity = wOCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_DISTRICT
     *
     * @return the value of w_order_detail.W_O_DISTRICT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwODistrict() {
        return wODistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_DISTRICT
     *
     * @param wODistrict the value for w_order_detail.W_O_DISTRICT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwODistrict(String wODistrict) {
        this.wODistrict = wODistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_TELEPHONE
     *
     * @return the value of w_order_detail.W_O_TELEPHONE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwOTelephone() {
        return wOTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_TELEPHONE
     *
     * @param wOTelephone the value for w_order_detail.W_O_TELEPHONE
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOTelephone(String wOTelephone) {
        this.wOTelephone = wOTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_ADDRESS
     *
     * @return the value of w_order_detail.W_O_ADDRESS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwOAddress() {
        return wOAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_ADDRESS
     *
     * @param wOAddress the value for w_order_detail.W_O_ADDRESS
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOAddress(String wOAddress) {
        this.wOAddress = wOAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_SUPPLIER_NAME
     *
     * @return the value of w_order_detail.W_O_SUPPLIER_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getwOSupplierName() {
        return wOSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_SUPPLIER_NAME
     *
     * @param wOSupplierName the value for w_order_detail.W_O_SUPPLIER_NAME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOSupplierName(String wOSupplierName) {
        this.wOSupplierName = wOSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_BEGIN_TIME
     *
     * @return the value of w_order_detail.W_O_BEGIN_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Date getwOBeginTime() {
        return wOBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_BEGIN_TIME
     *
     * @param wOBeginTime the value for w_order_detail.W_O_BEGIN_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOBeginTime(Date wOBeginTime) {
        this.wOBeginTime = wOBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_END_TIME
     *
     * @return the value of w_order_detail.W_O_END_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Date getwOEndTime() {
        return wOEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_END_TIME
     *
     * @param wOEndTime the value for w_order_detail.W_O_END_TIME
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOEndTime(Date wOEndTime) {
        this.wOEndTime = wOEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_HOUR
     *
     * @return the value of w_order_detail.W_O_HOUR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwOHour() {
        return wOHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_HOUR
     *
     * @param wOHour the value for w_order_detail.W_O_HOUR
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOHour(Integer wOHour) {
        this.wOHour = wOHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.W_O_STAFF_COUNT
     *
     * @return the value of w_order_detail.W_O_STAFF_COUNT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getwOStaffCount() {
        return wOStaffCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.W_O_STAFF_COUNT
     *
     * @param wOStaffCount the value for w_order_detail.W_O_STAFF_COUNT
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setwOStaffCount(Integer wOStaffCount) {
        this.wOStaffCount = wOStaffCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_order_detail.DATALEVEL
     *
     * @return the value of w_order_detail.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_order_detail.DATALEVEL
     *
     * @param datalevel the value for w_order_detail.DATALEVEL
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }
}