package com.umbrella.worker.entity;

import java.util.ArrayList;
import java.util.List;

public class WRatinExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public WRatinExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdIsNull() {
            addCriterion("W_R_SCHEDULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdIsNotNull() {
            addCriterion("W_R_SCHEDULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdEqualTo(Integer value) {
            addCriterion("W_R_SCHEDULE_ID =", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdNotEqualTo(Integer value) {
            addCriterion("W_R_SCHEDULE_ID <>", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdGreaterThan(Integer value) {
            addCriterion("W_R_SCHEDULE_ID >", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_R_SCHEDULE_ID >=", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdLessThan(Integer value) {
            addCriterion("W_R_SCHEDULE_ID <", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdLessThanOrEqualTo(Integer value) {
            addCriterion("W_R_SCHEDULE_ID <=", value, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdIn(List<Integer> values) {
            addCriterion("W_R_SCHEDULE_ID in", values, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdNotIn(List<Integer> values) {
            addCriterion("W_R_SCHEDULE_ID not in", values, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdBetween(Integer value1, Integer value2) {
            addCriterion("W_R_SCHEDULE_ID between", value1, value2, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScheduleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("W_R_SCHEDULE_ID not between", value1, value2, "wRScheduleId");
            return (Criteria) this;
        }

        public Criteria andWRScoreIsNull() {
            addCriterion("W_R_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andWRScoreIsNotNull() {
            addCriterion("W_R_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andWRScoreEqualTo(Integer value) {
            addCriterion("W_R_SCORE =", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreNotEqualTo(Integer value) {
            addCriterion("W_R_SCORE <>", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreGreaterThan(Integer value) {
            addCriterion("W_R_SCORE >", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_R_SCORE >=", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreLessThan(Integer value) {
            addCriterion("W_R_SCORE <", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreLessThanOrEqualTo(Integer value) {
            addCriterion("W_R_SCORE <=", value, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreIn(List<Integer> values) {
            addCriterion("W_R_SCORE in", values, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreNotIn(List<Integer> values) {
            addCriterion("W_R_SCORE not in", values, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreBetween(Integer value1, Integer value2) {
            addCriterion("W_R_SCORE between", value1, value2, "wRScore");
            return (Criteria) this;
        }

        public Criteria andWRScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("W_R_SCORE not between", value1, value2, "wRScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_ratin
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 29 12:03:32 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_ratin
     *
     * @mbggenerated Fri Jul 29 12:03:32 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}