package com.umbrella.worker.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WSmsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.S_SUPPLIER_ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Integer sSupplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.S_FEE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private BigDecimal sFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.S_MOBILE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private String sMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.CREATE_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.CREATE_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private String createAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.MODIFI_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Date modifiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.MODIFI_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private String modifiAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.DATALEVEL
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Integer datalevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sms_record.STATUS
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.ID
     *
     * @return the value of w_sms_record.ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.ID
     *
     * @param id the value for w_sms_record.ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.S_SUPPLIER_ID
     *
     * @return the value of w_sms_record.S_SUPPLIER_ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Integer getsSupplierId() {
        return sSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.S_SUPPLIER_ID
     *
     * @param sSupplierId the value for w_sms_record.S_SUPPLIER_ID
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setsSupplierId(Integer sSupplierId) {
        this.sSupplierId = sSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.S_FEE
     *
     * @return the value of w_sms_record.S_FEE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public BigDecimal getsFee() {
        return sFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.S_FEE
     *
     * @param sFee the value for w_sms_record.S_FEE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setsFee(BigDecimal sFee) {
        this.sFee = sFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.S_MOBILE
     *
     * @return the value of w_sms_record.S_MOBILE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public String getsMobile() {
        return sMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.S_MOBILE
     *
     * @param sMobile the value for w_sms_record.S_MOBILE
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setsMobile(String sMobile) {
        this.sMobile = sMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.CREATE_TIME
     *
     * @return the value of w_sms_record.CREATE_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.CREATE_TIME
     *
     * @param createTime the value for w_sms_record.CREATE_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.CREATE_AUTHOR
     *
     * @return the value of w_sms_record.CREATE_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.CREATE_AUTHOR
     *
     * @param createAuthor the value for w_sms_record.CREATE_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.MODIFI_TIME
     *
     * @return the value of w_sms_record.MODIFI_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Date getModifiTime() {
        return modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.MODIFI_TIME
     *
     * @param modifiTime the value for w_sms_record.MODIFI_TIME
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setModifiTime(Date modifiTime) {
        this.modifiTime = modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.MODIFI_AUTHOR
     *
     * @return the value of w_sms_record.MODIFI_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public String getModifiAuthor() {
        return modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.MODIFI_AUTHOR
     *
     * @param modifiAuthor the value for w_sms_record.MODIFI_AUTHOR
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setModifiAuthor(String modifiAuthor) {
        this.modifiAuthor = modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.DATALEVEL
     *
     * @return the value of w_sms_record.DATALEVEL
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.DATALEVEL
     *
     * @param datalevel the value for w_sms_record.DATALEVEL
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sms_record.STATUS
     *
     * @return the value of w_sms_record.STATUS
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sms_record.STATUS
     *
     * @param status the value for w_sms_record.STATUS
     *
     * @mbggenerated Wed Oct 19 04:53:48 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}