package com.umbrella.worker.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WStaffTimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    protected boolean distinct;
    protected String pageByClause;

    public String getPageByClause() {
		return pageByClause;
	}

	public void setPageByClause(String pageByClause) {
		this.pageByClause = pageByClause;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public WStaffTimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTStaffIdIsNull() {
            addCriterion("T_STAFF_ID is null");
            return (Criteria) this;
        }

        public Criteria andTStaffIdIsNotNull() {
            addCriterion("T_STAFF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTStaffIdEqualTo(Integer value) {
            addCriterion("T_STAFF_ID =", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdNotEqualTo(Integer value) {
            addCriterion("T_STAFF_ID <>", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdGreaterThan(Integer value) {
            addCriterion("T_STAFF_ID >", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("T_STAFF_ID >=", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdLessThan(Integer value) {
            addCriterion("T_STAFF_ID <", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("T_STAFF_ID <=", value, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdIn(List<Integer> values) {
            addCriterion("T_STAFF_ID in", values, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdNotIn(List<Integer> values) {
            addCriterion("T_STAFF_ID not in", values, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("T_STAFF_ID between", value1, value2, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("T_STAFF_ID not between", value1, value2, "tStaffId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdIsNull() {
            addCriterion("T_SUPPLIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdIsNotNull() {
            addCriterion("T_SUPPLIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdEqualTo(Integer value) {
            addCriterion("T_SUPPLIER_ID =", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdNotEqualTo(Integer value) {
            addCriterion("T_SUPPLIER_ID <>", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdGreaterThan(Integer value) {
            addCriterion("T_SUPPLIER_ID >", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("T_SUPPLIER_ID >=", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdLessThan(Integer value) {
            addCriterion("T_SUPPLIER_ID <", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdLessThanOrEqualTo(Integer value) {
            addCriterion("T_SUPPLIER_ID <=", value, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdIn(List<Integer> values) {
            addCriterion("T_SUPPLIER_ID in", values, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdNotIn(List<Integer> values) {
            addCriterion("T_SUPPLIER_ID not in", values, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdBetween(Integer value1, Integer value2) {
            addCriterion("T_SUPPLIER_ID between", value1, value2, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTSupplierIdNotBetween(Integer value1, Integer value2) {
            addCriterion("T_SUPPLIER_ID not between", value1, value2, "tSupplierId");
            return (Criteria) this;
        }

        public Criteria andTServiceNameIsNull() {
            addCriterion("T_SERVICE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTServiceNameIsNotNull() {
            addCriterion("T_SERVICE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTServiceNameEqualTo(String value) {
            addCriterion("T_SERVICE_NAME =", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameNotEqualTo(String value) {
            addCriterion("T_SERVICE_NAME <>", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameGreaterThan(String value) {
            addCriterion("T_SERVICE_NAME >", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("T_SERVICE_NAME >=", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameLessThan(String value) {
            addCriterion("T_SERVICE_NAME <", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameLessThanOrEqualTo(String value) {
            addCriterion("T_SERVICE_NAME <=", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameLike(String value) {
            addCriterion("T_SERVICE_NAME like", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameNotLike(String value) {
            addCriterion("T_SERVICE_NAME not like", value, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameIn(List<String> values) {
            addCriterion("T_SERVICE_NAME in", values, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameNotIn(List<String> values) {
            addCriterion("T_SERVICE_NAME not in", values, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameBetween(String value1, String value2) {
            addCriterion("T_SERVICE_NAME between", value1, value2, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTServiceNameNotBetween(String value1, String value2) {
            addCriterion("T_SERVICE_NAME not between", value1, value2, "tServiceName");
            return (Criteria) this;
        }

        public Criteria andTOrdernoIsNull() {
            addCriterion("T_ORDERNO is null");
            return (Criteria) this;
        }

        public Criteria andTOrdernoIsNotNull() {
            addCriterion("T_ORDERNO is not null");
            return (Criteria) this;
        }

        public Criteria andTOrdernoEqualTo(String value) {
            addCriterion("T_ORDERNO =", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoNotEqualTo(String value) {
            addCriterion("T_ORDERNO <>", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoGreaterThan(String value) {
            addCriterion("T_ORDERNO >", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("T_ORDERNO >=", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoLessThan(String value) {
            addCriterion("T_ORDERNO <", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoLessThanOrEqualTo(String value) {
            addCriterion("T_ORDERNO <=", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoLike(String value) {
            addCriterion("T_ORDERNO like", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoNotLike(String value) {
            addCriterion("T_ORDERNO not like", value, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoIn(List<String> values) {
            addCriterion("T_ORDERNO in", values, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoNotIn(List<String> values) {
            addCriterion("T_ORDERNO not in", values, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoBetween(String value1, String value2) {
            addCriterion("T_ORDERNO between", value1, value2, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTOrdernoNotBetween(String value1, String value2) {
            addCriterion("T_ORDERNO not between", value1, value2, "tOrderno");
            return (Criteria) this;
        }

        public Criteria andTStaffNameIsNull() {
            addCriterion("T_STAFF_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTStaffNameIsNotNull() {
            addCriterion("T_STAFF_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTStaffNameEqualTo(String value) {
            addCriterion("T_STAFF_NAME =", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameNotEqualTo(String value) {
            addCriterion("T_STAFF_NAME <>", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameGreaterThan(String value) {
            addCriterion("T_STAFF_NAME >", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("T_STAFF_NAME >=", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameLessThan(String value) {
            addCriterion("T_STAFF_NAME <", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameLessThanOrEqualTo(String value) {
            addCriterion("T_STAFF_NAME <=", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameLike(String value) {
            addCriterion("T_STAFF_NAME like", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameNotLike(String value) {
            addCriterion("T_STAFF_NAME not like", value, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameIn(List<String> values) {
            addCriterion("T_STAFF_NAME in", values, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameNotIn(List<String> values) {
            addCriterion("T_STAFF_NAME not in", values, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameBetween(String value1, String value2) {
            addCriterion("T_STAFF_NAME between", value1, value2, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffNameNotBetween(String value1, String value2) {
            addCriterion("T_STAFF_NAME not between", value1, value2, "tStaffName");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileIsNull() {
            addCriterion("T_STAFF_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileIsNotNull() {
            addCriterion("T_STAFF_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileEqualTo(String value) {
            addCriterion("T_STAFF_MOBILE =", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileNotEqualTo(String value) {
            addCriterion("T_STAFF_MOBILE <>", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileGreaterThan(String value) {
            addCriterion("T_STAFF_MOBILE >", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileGreaterThanOrEqualTo(String value) {
            addCriterion("T_STAFF_MOBILE >=", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileLessThan(String value) {
            addCriterion("T_STAFF_MOBILE <", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileLessThanOrEqualTo(String value) {
            addCriterion("T_STAFF_MOBILE <=", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileLike(String value) {
            addCriterion("T_STAFF_MOBILE like", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileNotLike(String value) {
            addCriterion("T_STAFF_MOBILE not like", value, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileIn(List<String> values) {
            addCriterion("T_STAFF_MOBILE in", values, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileNotIn(List<String> values) {
            addCriterion("T_STAFF_MOBILE not in", values, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileBetween(String value1, String value2) {
            addCriterion("T_STAFF_MOBILE between", value1, value2, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStaffMobileNotBetween(String value1, String value2) {
            addCriterion("T_STAFF_MOBILE not between", value1, value2, "tStaffMobile");
            return (Criteria) this;
        }

        public Criteria andTStartTimeIsNull() {
            addCriterion("T_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTStartTimeIsNotNull() {
            addCriterion("T_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTStartTimeEqualTo(Date value) {
            addCriterion("T_START_TIME =", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeNotEqualTo(Date value) {
            addCriterion("T_START_TIME <>", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeGreaterThan(Date value) {
            addCriterion("T_START_TIME >", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("T_START_TIME >=", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeLessThan(Date value) {
            addCriterion("T_START_TIME <", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("T_START_TIME <=", value, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeIn(List<Date> values) {
            addCriterion("T_START_TIME in", values, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeNotIn(List<Date> values) {
            addCriterion("T_START_TIME not in", values, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeBetween(Date value1, Date value2) {
            addCriterion("T_START_TIME between", value1, value2, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("T_START_TIME not between", value1, value2, "tStartTime");
            return (Criteria) this;
        }

        public Criteria andTMemberNameIsNull() {
            addCriterion("T_MEMBER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTMemberNameIsNotNull() {
            addCriterion("T_MEMBER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTMemberNameEqualTo(String value) {
            addCriterion("T_MEMBER_NAME =", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameNotEqualTo(String value) {
            addCriterion("T_MEMBER_NAME <>", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameGreaterThan(String value) {
            addCriterion("T_MEMBER_NAME >", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("T_MEMBER_NAME >=", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameLessThan(String value) {
            addCriterion("T_MEMBER_NAME <", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameLessThanOrEqualTo(String value) {
            addCriterion("T_MEMBER_NAME <=", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameLike(String value) {
            addCriterion("T_MEMBER_NAME like", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameNotLike(String value) {
            addCriterion("T_MEMBER_NAME not like", value, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameIn(List<String> values) {
            addCriterion("T_MEMBER_NAME in", values, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameNotIn(List<String> values) {
            addCriterion("T_MEMBER_NAME not in", values, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameBetween(String value1, String value2) {
            addCriterion("T_MEMBER_NAME between", value1, value2, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberNameNotBetween(String value1, String value2) {
            addCriterion("T_MEMBER_NAME not between", value1, value2, "tMemberName");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileIsNull() {
            addCriterion("T_MEMBER_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileIsNotNull() {
            addCriterion("T_MEMBER_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileEqualTo(String value) {
            addCriterion("T_MEMBER_MOBILE =", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileNotEqualTo(String value) {
            addCriterion("T_MEMBER_MOBILE <>", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileGreaterThan(String value) {
            addCriterion("T_MEMBER_MOBILE >", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileGreaterThanOrEqualTo(String value) {
            addCriterion("T_MEMBER_MOBILE >=", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileLessThan(String value) {
            addCriterion("T_MEMBER_MOBILE <", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileLessThanOrEqualTo(String value) {
            addCriterion("T_MEMBER_MOBILE <=", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileLike(String value) {
            addCriterion("T_MEMBER_MOBILE like", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileNotLike(String value) {
            addCriterion("T_MEMBER_MOBILE not like", value, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileIn(List<String> values) {
            addCriterion("T_MEMBER_MOBILE in", values, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileNotIn(List<String> values) {
            addCriterion("T_MEMBER_MOBILE not in", values, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileBetween(String value1, String value2) {
            addCriterion("T_MEMBER_MOBILE between", value1, value2, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTMemberMobileNotBetween(String value1, String value2) {
            addCriterion("T_MEMBER_MOBILE not between", value1, value2, "tMemberMobile");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIsNull() {
            addCriterion("T_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIsNotNull() {
            addCriterion("T_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTEndTimeEqualTo(Date value) {
            addCriterion("T_END_TIME =", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotEqualTo(Date value) {
            addCriterion("T_END_TIME <>", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeGreaterThan(Date value) {
            addCriterion("T_END_TIME >", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("T_END_TIME >=", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeLessThan(Date value) {
            addCriterion("T_END_TIME <", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("T_END_TIME <=", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIn(List<Date> values) {
            addCriterion("T_END_TIME in", values, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotIn(List<Date> values) {
            addCriterion("T_END_TIME not in", values, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeBetween(Date value1, Date value2) {
            addCriterion("T_END_TIME between", value1, value2, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("T_END_TIME not between", value1, value2, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNull() {
            addCriterion("CREATE_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNotNull() {
            addCriterion("CREATE_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorEqualTo(String value) {
            addCriterion("CREATE_AUTHOR =", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <>", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThan(String value) {
            addCriterion("CREATE_AUTHOR >", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR >=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThan(String value) {
            addCriterion("CREATE_AUTHOR <", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLike(String value) {
            addCriterion("CREATE_AUTHOR like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotLike(String value) {
            addCriterion("CREATE_AUTHOR not like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIn(List<String> values) {
            addCriterion("CREATE_AUTHOR in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotIn(List<String> values) {
            addCriterion("CREATE_AUTHOR not in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR not between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNull() {
            addCriterion("MODIFI_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNotNull() {
            addCriterion("MODIFI_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeEqualTo(Date value) {
            addCriterion("MODIFI_TIME =", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotEqualTo(Date value) {
            addCriterion("MODIFI_TIME <>", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThan(Date value) {
            addCriterion("MODIFI_TIME >", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME >=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThan(Date value) {
            addCriterion("MODIFI_TIME <", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME <=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIn(List<Date> values) {
            addCriterion("MODIFI_TIME in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotIn(List<Date> values) {
            addCriterion("MODIFI_TIME not in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME not between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNull() {
            addCriterion("MODIFI_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNotNull() {
            addCriterion("MODIFI_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR =", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <>", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThan(String value) {
            addCriterion("MODIFI_AUTHOR >", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR >=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThan(String value) {
            addCriterion("MODIFI_AUTHOR <", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLike(String value) {
            addCriterion("MODIFI_AUTHOR like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotLike(String value) {
            addCriterion("MODIFI_AUTHOR not like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR not in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR not between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNull() {
            addCriterion("DATALEVEL is null");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNotNull() {
            addCriterion("DATALEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andDatalevelEqualTo(Integer value) {
            addCriterion("DATALEVEL =", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotEqualTo(Integer value) {
            addCriterion("DATALEVEL <>", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThan(Integer value) {
            addCriterion("DATALEVEL >", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL >=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThan(Integer value) {
            addCriterion("DATALEVEL <", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL <=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelIn(List<Integer> values) {
            addCriterion("DATALEVEL in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotIn(List<Integer> values) {
            addCriterion("DATALEVEL not in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL between", value1, value2, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL not between", value1, value2, "datalevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff_time
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 30 20:21:25 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff_time
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}