package com.umbrella.worker.entity;

import java.util.Date;

public class WStaffTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_STAFF_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Integer tStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_SUPPLIER_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Integer tSupplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_SERVICE_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tServiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_ORDERNO
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tOrderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_STAFF_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tStaffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_STAFF_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tStaffMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_START_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Date tStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_MEMBER_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tMemberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_MEMBER_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String tMemberMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.T_END_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Date tEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.CREATE_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.CREATE_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String createAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.MODIFI_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Date modifiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.MODIFI_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private String modifiAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.STATUS
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_staff_time.DATALEVEL
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    private Integer datalevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.ID
     *
     * @return the value of w_staff_time.ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.ID
     *
     * @param id the value for w_staff_time.ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_STAFF_ID
     *
     * @return the value of w_staff_time.T_STAFF_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Integer gettStaffId() {
        return tStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_STAFF_ID
     *
     * @param tStaffId the value for w_staff_time.T_STAFF_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settStaffId(Integer tStaffId) {
        this.tStaffId = tStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_SUPPLIER_ID
     *
     * @return the value of w_staff_time.T_SUPPLIER_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Integer gettSupplierId() {
        return tSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_SUPPLIER_ID
     *
     * @param tSupplierId the value for w_staff_time.T_SUPPLIER_ID
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settSupplierId(Integer tSupplierId) {
        this.tSupplierId = tSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_SERVICE_NAME
     *
     * @return the value of w_staff_time.T_SERVICE_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettServiceName() {
        return tServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_SERVICE_NAME
     *
     * @param tServiceName the value for w_staff_time.T_SERVICE_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settServiceName(String tServiceName) {
        this.tServiceName = tServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_ORDERNO
     *
     * @return the value of w_staff_time.T_ORDERNO
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettOrderno() {
        return tOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_ORDERNO
     *
     * @param tOrderno the value for w_staff_time.T_ORDERNO
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settOrderno(String tOrderno) {
        this.tOrderno = tOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_STAFF_NAME
     *
     * @return the value of w_staff_time.T_STAFF_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettStaffName() {
        return tStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_STAFF_NAME
     *
     * @param tStaffName the value for w_staff_time.T_STAFF_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settStaffName(String tStaffName) {
        this.tStaffName = tStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_STAFF_MOBILE
     *
     * @return the value of w_staff_time.T_STAFF_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettStaffMobile() {
        return tStaffMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_STAFF_MOBILE
     *
     * @param tStaffMobile the value for w_staff_time.T_STAFF_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settStaffMobile(String tStaffMobile) {
        this.tStaffMobile = tStaffMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_START_TIME
     *
     * @return the value of w_staff_time.T_START_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Date gettStartTime() {
        return tStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_START_TIME
     *
     * @param tStartTime the value for w_staff_time.T_START_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settStartTime(Date tStartTime) {
        this.tStartTime = tStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_MEMBER_NAME
     *
     * @return the value of w_staff_time.T_MEMBER_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettMemberName() {
        return tMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_MEMBER_NAME
     *
     * @param tMemberName the value for w_staff_time.T_MEMBER_NAME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settMemberName(String tMemberName) {
        this.tMemberName = tMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_MEMBER_MOBILE
     *
     * @return the value of w_staff_time.T_MEMBER_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String gettMemberMobile() {
        return tMemberMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_MEMBER_MOBILE
     *
     * @param tMemberMobile the value for w_staff_time.T_MEMBER_MOBILE
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settMemberMobile(String tMemberMobile) {
        this.tMemberMobile = tMemberMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.T_END_TIME
     *
     * @return the value of w_staff_time.T_END_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Date gettEndTime() {
        return tEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.T_END_TIME
     *
     * @param tEndTime the value for w_staff_time.T_END_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void settEndTime(Date tEndTime) {
        this.tEndTime = tEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.CREATE_TIME
     *
     * @return the value of w_staff_time.CREATE_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.CREATE_TIME
     *
     * @param createTime the value for w_staff_time.CREATE_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.CREATE_AUTHOR
     *
     * @return the value of w_staff_time.CREATE_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.CREATE_AUTHOR
     *
     * @param createAuthor the value for w_staff_time.CREATE_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.MODIFI_TIME
     *
     * @return the value of w_staff_time.MODIFI_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Date getModifiTime() {
        return modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.MODIFI_TIME
     *
     * @param modifiTime the value for w_staff_time.MODIFI_TIME
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setModifiTime(Date modifiTime) {
        this.modifiTime = modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.MODIFI_AUTHOR
     *
     * @return the value of w_staff_time.MODIFI_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public String getModifiAuthor() {
        return modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.MODIFI_AUTHOR
     *
     * @param modifiAuthor the value for w_staff_time.MODIFI_AUTHOR
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setModifiAuthor(String modifiAuthor) {
        this.modifiAuthor = modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.STATUS
     *
     * @return the value of w_staff_time.STATUS
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.STATUS
     *
     * @param status the value for w_staff_time.STATUS
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_staff_time.DATALEVEL
     *
     * @return the value of w_staff_time.DATALEVEL
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_staff_time.DATALEVEL
     *
     * @param datalevel the value for w_staff_time.DATALEVEL
     *
     * @mbggenerated Sun Oct 30 20:21:25 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }
}