package com.umbrella.worker.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WStaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected boolean distinct;
    
    protected String pageByClause;

    public String getPageByClause() {
		return pageByClause;
	}

	public void setPageByClause(String pageByClause) {
		this.pageByClause = pageByClause;
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public WStaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdIsNull() {
            addCriterion("W_S_SUPPLIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdIsNotNull() {
            addCriterion("W_S_SUPPLIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdEqualTo(Integer value) {
            addCriterion("W_S_SUPPLIER_ID =", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdNotEqualTo(Integer value) {
            addCriterion("W_S_SUPPLIER_ID <>", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdGreaterThan(Integer value) {
            addCriterion("W_S_SUPPLIER_ID >", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_SUPPLIER_ID >=", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdLessThan(Integer value) {
            addCriterion("W_S_SUPPLIER_ID <", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_SUPPLIER_ID <=", value, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdIn(List<Integer> values) {
            addCriterion("W_S_SUPPLIER_ID in", values, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdNotIn(List<Integer> values) {
            addCriterion("W_S_SUPPLIER_ID not in", values, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SUPPLIER_ID between", value1, value2, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSSupplierIdNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SUPPLIER_ID not between", value1, value2, "wSSupplierId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIsNull() {
            addCriterion("W_S_ATTAC_ID is null");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIsNotNull() {
            addCriterion("W_S_ATTAC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID =", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID <>", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdGreaterThan(Integer value) {
            addCriterion("W_S_ATTAC_ID >", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID >=", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdLessThan(Integer value) {
            addCriterion("W_S_ATTAC_ID <", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID <=", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIn(List<Integer> values) {
            addCriterion("W_S_ATTAC_ID in", values, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotIn(List<Integer> values) {
            addCriterion("W_S_ATTAC_ID not in", values, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdBetween(Integer value1, Integer value2) {
            addCriterion("W_S_ATTAC_ID between", value1, value2, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_ATTAC_ID not between", value1, value2, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWStaffNameIsNull() {
            addCriterion("W_STAFF_NAME is null");
            return (Criteria) this;
        }

        public Criteria andWStaffNameIsNotNull() {
            addCriterion("W_STAFF_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andWStaffNameEqualTo(String value) {
            addCriterion("W_STAFF_NAME =", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameNotEqualTo(String value) {
            addCriterion("W_STAFF_NAME <>", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameGreaterThan(String value) {
            addCriterion("W_STAFF_NAME >", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("W_STAFF_NAME >=", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameLessThan(String value) {
            addCriterion("W_STAFF_NAME <", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameLessThanOrEqualTo(String value) {
            addCriterion("W_STAFF_NAME <=", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameLike(String value) {
            addCriterion("W_STAFF_NAME like", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameNotLike(String value) {
            addCriterion("W_STAFF_NAME not like", value, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameIn(List<String> values) {
            addCriterion("W_STAFF_NAME in", values, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameNotIn(List<String> values) {
            addCriterion("W_STAFF_NAME not in", values, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameBetween(String value1, String value2) {
            addCriterion("W_STAFF_NAME between", value1, value2, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffNameNotBetween(String value1, String value2) {
            addCriterion("W_STAFF_NAME not between", value1, value2, "wStaffName");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderIsNull() {
            addCriterion("W_STAFF_GENDER is null");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderIsNotNull() {
            addCriterion("W_STAFF_GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderEqualTo(Integer value) {
            addCriterion("W_STAFF_GENDER =", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderNotEqualTo(Integer value) {
            addCriterion("W_STAFF_GENDER <>", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderGreaterThan(Integer value) {
            addCriterion("W_STAFF_GENDER >", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_STAFF_GENDER >=", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderLessThan(Integer value) {
            addCriterion("W_STAFF_GENDER <", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderLessThanOrEqualTo(Integer value) {
            addCriterion("W_STAFF_GENDER <=", value, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderIn(List<Integer> values) {
            addCriterion("W_STAFF_GENDER in", values, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderNotIn(List<Integer> values) {
            addCriterion("W_STAFF_GENDER not in", values, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderBetween(Integer value1, Integer value2) {
            addCriterion("W_STAFF_GENDER between", value1, value2, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWStaffGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("W_STAFF_GENDER not between", value1, value2, "wStaffGender");
            return (Criteria) this;
        }

        public Criteria andWSIdcardIsNull() {
            addCriterion("W_S_IDCARD is null");
            return (Criteria) this;
        }

        public Criteria andWSIdcardIsNotNull() {
            addCriterion("W_S_IDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andWSIdcardEqualTo(String value) {
            addCriterion("W_S_IDCARD =", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardNotEqualTo(String value) {
            addCriterion("W_S_IDCARD <>", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardGreaterThan(String value) {
            addCriterion("W_S_IDCARD >", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_IDCARD >=", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardLessThan(String value) {
            addCriterion("W_S_IDCARD <", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardLessThanOrEqualTo(String value) {
            addCriterion("W_S_IDCARD <=", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardLike(String value) {
            addCriterion("W_S_IDCARD like", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardNotLike(String value) {
            addCriterion("W_S_IDCARD not like", value, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardIn(List<String> values) {
            addCriterion("W_S_IDCARD in", values, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardNotIn(List<String> values) {
            addCriterion("W_S_IDCARD not in", values, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardBetween(String value1, String value2) {
            addCriterion("W_S_IDCARD between", value1, value2, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSIdcardNotBetween(String value1, String value2) {
            addCriterion("W_S_IDCARD not between", value1, value2, "wSIdcard");
            return (Criteria) this;
        }

        public Criteria andWSAgeIsNull() {
            addCriterion("W_S_AGE is null");
            return (Criteria) this;
        }

        public Criteria andWSAgeIsNotNull() {
            addCriterion("W_S_AGE is not null");
            return (Criteria) this;
        }

        public Criteria andWSAgeEqualTo(Integer value) {
            addCriterion("W_S_AGE =", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeNotEqualTo(Integer value) {
            addCriterion("W_S_AGE <>", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeGreaterThan(Integer value) {
            addCriterion("W_S_AGE >", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_AGE >=", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeLessThan(Integer value) {
            addCriterion("W_S_AGE <", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_AGE <=", value, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeIn(List<Integer> values) {
            addCriterion("W_S_AGE in", values, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeNotIn(List<Integer> values) {
            addCriterion("W_S_AGE not in", values, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeBetween(Integer value1, Integer value2) {
            addCriterion("W_S_AGE between", value1, value2, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_AGE not between", value1, value2, "wSAge");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearIsNull() {
            addCriterion("W_S_WOKER_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearIsNotNull() {
            addCriterion("W_S_WOKER_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearEqualTo(Integer value) {
            addCriterion("W_S_WOKER_YEAR =", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearNotEqualTo(Integer value) {
            addCriterion("W_S_WOKER_YEAR <>", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearGreaterThan(Integer value) {
            addCriterion("W_S_WOKER_YEAR >", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_WOKER_YEAR >=", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearLessThan(Integer value) {
            addCriterion("W_S_WOKER_YEAR <", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_WOKER_YEAR <=", value, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearIn(List<Integer> values) {
            addCriterion("W_S_WOKER_YEAR in", values, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearNotIn(List<Integer> values) {
            addCriterion("W_S_WOKER_YEAR not in", values, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearBetween(Integer value1, Integer value2) {
            addCriterion("W_S_WOKER_YEAR between", value1, value2, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSWokerYearNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_WOKER_YEAR not between", value1, value2, "wSWokerYear");
            return (Criteria) this;
        }

        public Criteria andWSGradeIsNull() {
            addCriterion("W_S_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andWSGradeIsNotNull() {
            addCriterion("W_S_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andWSGradeEqualTo(Integer value) {
            addCriterion("W_S_GRADE =", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotEqualTo(Integer value) {
            addCriterion("W_S_GRADE <>", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeGreaterThan(Integer value) {
            addCriterion("W_S_GRADE >", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_GRADE >=", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeLessThan(Integer value) {
            addCriterion("W_S_GRADE <", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_GRADE <=", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeIn(List<Integer> values) {
            addCriterion("W_S_GRADE in", values, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotIn(List<Integer> values) {
            addCriterion("W_S_GRADE not in", values, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeBetween(Integer value1, Integer value2) {
            addCriterion("W_S_GRADE between", value1, value2, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_GRADE not between", value1, value2, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSTypeIsNull() {
            addCriterion("W_S_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andWSTypeIsNotNull() {
            addCriterion("W_S_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andWSTypeEqualTo(Integer value) {
            addCriterion("W_S_TYPE =", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeNotEqualTo(Integer value) {
            addCriterion("W_S_TYPE <>", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeGreaterThan(Integer value) {
            addCriterion("W_S_TYPE >", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_TYPE >=", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeLessThan(Integer value) {
            addCriterion("W_S_TYPE <", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_TYPE <=", value, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeIn(List<Integer> values) {
            addCriterion("W_S_TYPE in", values, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeNotIn(List<Integer> values) {
            addCriterion("W_S_TYPE not in", values, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeBetween(Integer value1, Integer value2) {
            addCriterion("W_S_TYPE between", value1, value2, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_TYPE not between", value1, value2, "wSType");
            return (Criteria) this;
        }

        public Criteria andWSScoreIsNull() {
            addCriterion("W_S_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andWSScoreIsNotNull() {
            addCriterion("W_S_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andWSScoreEqualTo(Integer value) {
            addCriterion("W_S_SCORE =", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreNotEqualTo(Integer value) {
            addCriterion("W_S_SCORE <>", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreGreaterThan(Integer value) {
            addCriterion("W_S_SCORE >", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_SCORE >=", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreLessThan(Integer value) {
            addCriterion("W_S_SCORE <", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_SCORE <=", value, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreIn(List<Integer> values) {
            addCriterion("W_S_SCORE in", values, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreNotIn(List<Integer> values) {
            addCriterion("W_S_SCORE not in", values, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SCORE between", value1, value2, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SCORE not between", value1, value2, "wSScore");
            return (Criteria) this;
        }

        public Criteria andWSAddressIsNull() {
            addCriterion("W_S_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andWSAddressIsNotNull() {
            addCriterion("W_S_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andWSAddressEqualTo(String value) {
            addCriterion("W_S_ADDRESS =", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotEqualTo(String value) {
            addCriterion("W_S_ADDRESS <>", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressGreaterThan(String value) {
            addCriterion("W_S_ADDRESS >", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_ADDRESS >=", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLessThan(String value) {
            addCriterion("W_S_ADDRESS <", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLessThanOrEqualTo(String value) {
            addCriterion("W_S_ADDRESS <=", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLike(String value) {
            addCriterion("W_S_ADDRESS like", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotLike(String value) {
            addCriterion("W_S_ADDRESS not like", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressIn(List<String> values) {
            addCriterion("W_S_ADDRESS in", values, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotIn(List<String> values) {
            addCriterion("W_S_ADDRESS not in", values, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressBetween(String value1, String value2) {
            addCriterion("W_S_ADDRESS between", value1, value2, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotBetween(String value1, String value2) {
            addCriterion("W_S_ADDRESS not between", value1, value2, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIsNull() {
            addCriterion("W_S_TELEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIsNotNull() {
            addCriterion("W_S_TELEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneEqualTo(String value) {
            addCriterion("W_S_TELEPHONE =", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotEqualTo(String value) {
            addCriterion("W_S_TELEPHONE <>", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneGreaterThan(String value) {
            addCriterion("W_S_TELEPHONE >", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_TELEPHONE >=", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLessThan(String value) {
            addCriterion("W_S_TELEPHONE <", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLessThanOrEqualTo(String value) {
            addCriterion("W_S_TELEPHONE <=", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLike(String value) {
            addCriterion("W_S_TELEPHONE like", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotLike(String value) {
            addCriterion("W_S_TELEPHONE not like", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIn(List<String> values) {
            addCriterion("W_S_TELEPHONE in", values, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotIn(List<String> values) {
            addCriterion("W_S_TELEPHONE not in", values, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneBetween(String value1, String value2) {
            addCriterion("W_S_TELEPHONE between", value1, value2, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotBetween(String value1, String value2) {
            addCriterion("W_S_TELEPHONE not between", value1, value2, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSPlaceIsNull() {
            addCriterion("W_S_PLACE is null");
            return (Criteria) this;
        }

        public Criteria andWSPlaceIsNotNull() {
            addCriterion("W_S_PLACE is not null");
            return (Criteria) this;
        }

        public Criteria andWSPlaceEqualTo(String value) {
            addCriterion("W_S_PLACE =", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceNotEqualTo(String value) {
            addCriterion("W_S_PLACE <>", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceGreaterThan(String value) {
            addCriterion("W_S_PLACE >", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_PLACE >=", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceLessThan(String value) {
            addCriterion("W_S_PLACE <", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceLessThanOrEqualTo(String value) {
            addCriterion("W_S_PLACE <=", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceLike(String value) {
            addCriterion("W_S_PLACE like", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceNotLike(String value) {
            addCriterion("W_S_PLACE not like", value, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceIn(List<String> values) {
            addCriterion("W_S_PLACE in", values, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceNotIn(List<String> values) {
            addCriterion("W_S_PLACE not in", values, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceBetween(String value1, String value2) {
            addCriterion("W_S_PLACE between", value1, value2, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSPlaceNotBetween(String value1, String value2) {
            addCriterion("W_S_PLACE not between", value1, value2, "wSPlace");
            return (Criteria) this;
        }

        public Criteria andWSItemsIsNull() {
            addCriterion("W_S_ITEMS is null");
            return (Criteria) this;
        }

        public Criteria andWSItemsIsNotNull() {
            addCriterion("W_S_ITEMS is not null");
            return (Criteria) this;
        }

        public Criteria andWSItemsEqualTo(String value) {
            addCriterion("W_S_ITEMS =", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsNotEqualTo(String value) {
            addCriterion("W_S_ITEMS <>", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsGreaterThan(String value) {
            addCriterion("W_S_ITEMS >", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_ITEMS >=", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsLessThan(String value) {
            addCriterion("W_S_ITEMS <", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsLessThanOrEqualTo(String value) {
            addCriterion("W_S_ITEMS <=", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsLike(String value) {
            addCriterion("W_S_ITEMS like", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsNotLike(String value) {
            addCriterion("W_S_ITEMS not like", value, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsIn(List<String> values) {
            addCriterion("W_S_ITEMS in", values, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsNotIn(List<String> values) {
            addCriterion("W_S_ITEMS not in", values, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsBetween(String value1, String value2) {
            addCriterion("W_S_ITEMS between", value1, value2, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSItemsNotBetween(String value1, String value2) {
            addCriterion("W_S_ITEMS not between", value1, value2, "wSItems");
            return (Criteria) this;
        }

        public Criteria andWSTergetIsNull() {
            addCriterion("W_S_TERGET is null");
            return (Criteria) this;
        }

        public Criteria andWSTergetIsNotNull() {
            addCriterion("W_S_TERGET is not null");
            return (Criteria) this;
        }

        public Criteria andWSTergetEqualTo(String value) {
            addCriterion("W_S_TERGET =", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetNotEqualTo(String value) {
            addCriterion("W_S_TERGET <>", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetGreaterThan(String value) {
            addCriterion("W_S_TERGET >", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_TERGET >=", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetLessThan(String value) {
            addCriterion("W_S_TERGET <", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetLessThanOrEqualTo(String value) {
            addCriterion("W_S_TERGET <=", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetLike(String value) {
            addCriterion("W_S_TERGET like", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetNotLike(String value) {
            addCriterion("W_S_TERGET not like", value, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetIn(List<String> values) {
            addCriterion("W_S_TERGET in", values, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetNotIn(List<String> values) {
            addCriterion("W_S_TERGET not in", values, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetBetween(String value1, String value2) {
            addCriterion("W_S_TERGET between", value1, value2, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSTergetNotBetween(String value1, String value2) {
            addCriterion("W_S_TERGET not between", value1, value2, "wSTerget");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountIsNull() {
            addCriterion("W_S_WORK_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountIsNotNull() {
            addCriterion("W_S_WORK_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountEqualTo(Integer value) {
            addCriterion("W_S_WORK_COUNT =", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountNotEqualTo(Integer value) {
            addCriterion("W_S_WORK_COUNT <>", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountGreaterThan(Integer value) {
            addCriterion("W_S_WORK_COUNT >", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_WORK_COUNT >=", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountLessThan(Integer value) {
            addCriterion("W_S_WORK_COUNT <", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_WORK_COUNT <=", value, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountIn(List<Integer> values) {
            addCriterion("W_S_WORK_COUNT in", values, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountNotIn(List<Integer> values) {
            addCriterion("W_S_WORK_COUNT not in", values, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountBetween(Integer value1, Integer value2) {
            addCriterion("W_S_WORK_COUNT between", value1, value2, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSWorkCountNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_WORK_COUNT not between", value1, value2, "wSWorkCount");
            return (Criteria) this;
        }

        public Criteria andWSDescIsNull() {
            addCriterion("W_S_DESC is null");
            return (Criteria) this;
        }

        public Criteria andWSDescIsNotNull() {
            addCriterion("W_S_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andWSDescEqualTo(String value) {
            addCriterion("W_S_DESC =", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescNotEqualTo(String value) {
            addCriterion("W_S_DESC <>", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescGreaterThan(String value) {
            addCriterion("W_S_DESC >", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_DESC >=", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescLessThan(String value) {
            addCriterion("W_S_DESC <", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescLessThanOrEqualTo(String value) {
            addCriterion("W_S_DESC <=", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescLike(String value) {
            addCriterion("W_S_DESC like", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescNotLike(String value) {
            addCriterion("W_S_DESC not like", value, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescIn(List<String> values) {
            addCriterion("W_S_DESC in", values, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescNotIn(List<String> values) {
            addCriterion("W_S_DESC not in", values, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescBetween(String value1, String value2) {
            addCriterion("W_S_DESC between", value1, value2, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSDescNotBetween(String value1, String value2) {
            addCriterion("W_S_DESC not between", value1, value2, "wSDesc");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountIsNull() {
            addCriterion("W_S_COMPLAINT_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountIsNotNull() {
            addCriterion("W_S_COMPLAINT_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountEqualTo(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT =", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountNotEqualTo(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT <>", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountGreaterThan(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT >", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT >=", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountLessThan(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT <", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_COMPLAINT_COUNT <=", value, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountIn(List<Integer> values) {
            addCriterion("W_S_COMPLAINT_COUNT in", values, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountNotIn(List<Integer> values) {
            addCriterion("W_S_COMPLAINT_COUNT not in", values, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountBetween(Integer value1, Integer value2) {
            addCriterion("W_S_COMPLAINT_COUNT between", value1, value2, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSComplaintCountNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_COMPLAINT_COUNT not between", value1, value2, "wSComplaintCount");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstIsNull() {
            addCriterion("W_S_PRICE_FIRST is null");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstIsNotNull() {
            addCriterion("W_S_PRICE_FIRST is not null");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST =", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstNotEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST <>", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstGreaterThan(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST >", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST >=", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstLessThan(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST <", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstLessThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_FIRST <=", value, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_FIRST in", values, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstNotIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_FIRST not in", values, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_FIRST between", value1, value2, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceFirstNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_FIRST not between", value1, value2, "wSPriceFirst");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondIsNull() {
            addCriterion("W_S_PRICE_SECOND is null");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondIsNotNull() {
            addCriterion("W_S_PRICE_SECOND is not null");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND =", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondNotEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND <>", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondGreaterThan(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND >", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND >=", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondLessThan(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND <", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondLessThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_SECOND <=", value, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_SECOND in", values, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondNotIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_SECOND not in", values, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_SECOND between", value1, value2, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceSecondNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_SECOND not between", value1, value2, "wSPriceSecond");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridIsNull() {
            addCriterion("W_S_PRICE_THRID is null");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridIsNotNull() {
            addCriterion("W_S_PRICE_THRID is not null");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID =", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridNotEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID <>", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridGreaterThan(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID >", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID >=", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridLessThan(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID <", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridLessThanOrEqualTo(BigDecimal value) {
            addCriterion("W_S_PRICE_THRID <=", value, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_THRID in", values, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridNotIn(List<BigDecimal> values) {
            addCriterion("W_S_PRICE_THRID not in", values, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_THRID between", value1, value2, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSPriceThridNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("W_S_PRICE_THRID not between", value1, value2, "wSPriceThrid");
            return (Criteria) this;
        }

        public Criteria andWSRestDayIsNull() {
            addCriterion("W_S_REST_DAY is null");
            return (Criteria) this;
        }

        public Criteria andWSRestDayIsNotNull() {
            addCriterion("W_S_REST_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andWSRestDayEqualTo(Integer value) {
            addCriterion("W_S_REST_DAY =", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayNotEqualTo(Integer value) {
            addCriterion("W_S_REST_DAY <>", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayGreaterThan(Integer value) {
            addCriterion("W_S_REST_DAY >", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_REST_DAY >=", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayLessThan(Integer value) {
            addCriterion("W_S_REST_DAY <", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_REST_DAY <=", value, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayIn(List<Integer> values) {
            addCriterion("W_S_REST_DAY in", values, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayNotIn(List<Integer> values) {
            addCriterion("W_S_REST_DAY not in", values, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayBetween(Integer value1, Integer value2) {
            addCriterion("W_S_REST_DAY between", value1, value2, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSRestDayNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_REST_DAY not between", value1, value2, "wSRestDay");
            return (Criteria) this;
        }

        public Criteria andWSNationIsNull() {
            addCriterion("W_S_NATION is null");
            return (Criteria) this;
        }

        public Criteria andWSNationIsNotNull() {
            addCriterion("W_S_NATION is not null");
            return (Criteria) this;
        }

        public Criteria andWSNationEqualTo(String value) {
            addCriterion("W_S_NATION =", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationNotEqualTo(String value) {
            addCriterion("W_S_NATION <>", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationGreaterThan(String value) {
            addCriterion("W_S_NATION >", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_NATION >=", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationLessThan(String value) {
            addCriterion("W_S_NATION <", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationLessThanOrEqualTo(String value) {
            addCriterion("W_S_NATION <=", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationLike(String value) {
            addCriterion("W_S_NATION like", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationNotLike(String value) {
            addCriterion("W_S_NATION not like", value, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationIn(List<String> values) {
            addCriterion("W_S_NATION in", values, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationNotIn(List<String> values) {
            addCriterion("W_S_NATION not in", values, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationBetween(String value1, String value2) {
            addCriterion("W_S_NATION between", value1, value2, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSNationNotBetween(String value1, String value2) {
            addCriterion("W_S_NATION not between", value1, value2, "wSNation");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriIsNull() {
            addCriterion("W_S_IS_MARRI is null");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriIsNotNull() {
            addCriterion("W_S_IS_MARRI is not null");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriEqualTo(Integer value) {
            addCriterion("W_S_IS_MARRI =", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriNotEqualTo(Integer value) {
            addCriterion("W_S_IS_MARRI <>", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriGreaterThan(Integer value) {
            addCriterion("W_S_IS_MARRI >", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_IS_MARRI >=", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriLessThan(Integer value) {
            addCriterion("W_S_IS_MARRI <", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_IS_MARRI <=", value, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriIn(List<Integer> values) {
            addCriterion("W_S_IS_MARRI in", values, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriNotIn(List<Integer> values) {
            addCriterion("W_S_IS_MARRI not in", values, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriBetween(Integer value1, Integer value2) {
            addCriterion("W_S_IS_MARRI between", value1, value2, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSIsMarriNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_IS_MARRI not between", value1, value2, "wSIsMarri");
            return (Criteria) this;
        }

        public Criteria andWSAttributeIsNull() {
            addCriterion("W_S_ATTRIBUTE is null");
            return (Criteria) this;
        }

        public Criteria andWSAttributeIsNotNull() {
            addCriterion("W_S_ATTRIBUTE is not null");
            return (Criteria) this;
        }

        public Criteria andWSAttributeEqualTo(String value) {
            addCriterion("W_S_ATTRIBUTE =", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeNotEqualTo(String value) {
            addCriterion("W_S_ATTRIBUTE <>", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeGreaterThan(String value) {
            addCriterion("W_S_ATTRIBUTE >", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_ATTRIBUTE >=", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeLessThan(String value) {
            addCriterion("W_S_ATTRIBUTE <", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeLessThanOrEqualTo(String value) {
            addCriterion("W_S_ATTRIBUTE <=", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeLike(String value) {
            addCriterion("W_S_ATTRIBUTE like", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeNotLike(String value) {
            addCriterion("W_S_ATTRIBUTE not like", value, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeIn(List<String> values) {
            addCriterion("W_S_ATTRIBUTE in", values, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeNotIn(List<String> values) {
            addCriterion("W_S_ATTRIBUTE not in", values, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeBetween(String value1, String value2) {
            addCriterion("W_S_ATTRIBUTE between", value1, value2, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSAttributeNotBetween(String value1, String value2) {
            addCriterion("W_S_ATTRIBUTE not between", value1, value2, "wSAttribute");
            return (Criteria) this;
        }

        public Criteria andWSEduIsNull() {
            addCriterion("W_S_EDU is null");
            return (Criteria) this;
        }

        public Criteria andWSEduIsNotNull() {
            addCriterion("W_S_EDU is not null");
            return (Criteria) this;
        }

        public Criteria andWSEduEqualTo(String value) {
            addCriterion("W_S_EDU =", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduNotEqualTo(String value) {
            addCriterion("W_S_EDU <>", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduGreaterThan(String value) {
            addCriterion("W_S_EDU >", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_EDU >=", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduLessThan(String value) {
            addCriterion("W_S_EDU <", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduLessThanOrEqualTo(String value) {
            addCriterion("W_S_EDU <=", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduLike(String value) {
            addCriterion("W_S_EDU like", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduNotLike(String value) {
            addCriterion("W_S_EDU not like", value, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduIn(List<String> values) {
            addCriterion("W_S_EDU in", values, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduNotIn(List<String> values) {
            addCriterion("W_S_EDU not in", values, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduBetween(String value1, String value2) {
            addCriterion("W_S_EDU between", value1, value2, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSEduNotBetween(String value1, String value2) {
            addCriterion("W_S_EDU not between", value1, value2, "wSEdu");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgIsNull() {
            addCriterion("W_S_TRAIN_ORG is null");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgIsNotNull() {
            addCriterion("W_S_TRAIN_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgEqualTo(String value) {
            addCriterion("W_S_TRAIN_ORG =", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgNotEqualTo(String value) {
            addCriterion("W_S_TRAIN_ORG <>", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgGreaterThan(String value) {
            addCriterion("W_S_TRAIN_ORG >", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_TRAIN_ORG >=", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgLessThan(String value) {
            addCriterion("W_S_TRAIN_ORG <", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgLessThanOrEqualTo(String value) {
            addCriterion("W_S_TRAIN_ORG <=", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgLike(String value) {
            addCriterion("W_S_TRAIN_ORG like", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgNotLike(String value) {
            addCriterion("W_S_TRAIN_ORG not like", value, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgIn(List<String> values) {
            addCriterion("W_S_TRAIN_ORG in", values, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgNotIn(List<String> values) {
            addCriterion("W_S_TRAIN_ORG not in", values, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgBetween(String value1, String value2) {
            addCriterion("W_S_TRAIN_ORG between", value1, value2, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainOrgNotBetween(String value1, String value2) {
            addCriterion("W_S_TRAIN_ORG not between", value1, value2, "wSTrainOrg");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateIsNull() {
            addCriterion("W_S_TRAIN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateIsNotNull() {
            addCriterion("W_S_TRAIN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateEqualTo(Date value) {
            addCriterion("W_S_TRAIN_DATE =", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateNotEqualTo(Date value) {
            addCriterion("W_S_TRAIN_DATE <>", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateGreaterThan(Date value) {
            addCriterion("W_S_TRAIN_DATE >", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateGreaterThanOrEqualTo(Date value) {
            addCriterion("W_S_TRAIN_DATE >=", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateLessThan(Date value) {
            addCriterion("W_S_TRAIN_DATE <", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateLessThanOrEqualTo(Date value) {
            addCriterion("W_S_TRAIN_DATE <=", value, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateIn(List<Date> values) {
            addCriterion("W_S_TRAIN_DATE in", values, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateNotIn(List<Date> values) {
            addCriterion("W_S_TRAIN_DATE not in", values, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateBetween(Date value1, Date value2) {
            addCriterion("W_S_TRAIN_DATE between", value1, value2, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainDateNotBetween(Date value1, Date value2) {
            addCriterion("W_S_TRAIN_DATE not between", value1, value2, "wSTrainDate");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsIsNull() {
            addCriterion("w_S_TRAIN_ITEMS is null");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsIsNotNull() {
            addCriterion("w_S_TRAIN_ITEMS is not null");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsEqualTo(String value) {
            addCriterion("w_S_TRAIN_ITEMS =", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsNotEqualTo(String value) {
            addCriterion("w_S_TRAIN_ITEMS <>", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsGreaterThan(String value) {
            addCriterion("w_S_TRAIN_ITEMS >", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsGreaterThanOrEqualTo(String value) {
            addCriterion("w_S_TRAIN_ITEMS >=", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsLessThan(String value) {
            addCriterion("w_S_TRAIN_ITEMS <", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsLessThanOrEqualTo(String value) {
            addCriterion("w_S_TRAIN_ITEMS <=", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsLike(String value) {
            addCriterion("w_S_TRAIN_ITEMS like", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsNotLike(String value) {
            addCriterion("w_S_TRAIN_ITEMS not like", value, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsIn(List<String> values) {
            addCriterion("w_S_TRAIN_ITEMS in", values, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsNotIn(List<String> values) {
            addCriterion("w_S_TRAIN_ITEMS not in", values, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsBetween(String value1, String value2) {
            addCriterion("w_S_TRAIN_ITEMS between", value1, value2, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andWSTrainItemsNotBetween(String value1, String value2) {
            addCriterion("w_S_TRAIN_ITEMS not between", value1, value2, "wSTrainItems");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNull() {
            addCriterion("CREATE_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNotNull() {
            addCriterion("CREATE_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorEqualTo(String value) {
            addCriterion("CREATE_AUTHOR =", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <>", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThan(String value) {
            addCriterion("CREATE_AUTHOR >", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR >=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThan(String value) {
            addCriterion("CREATE_AUTHOR <", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLike(String value) {
            addCriterion("CREATE_AUTHOR like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotLike(String value) {
            addCriterion("CREATE_AUTHOR not like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIn(List<String> values) {
            addCriterion("CREATE_AUTHOR in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotIn(List<String> values) {
            addCriterion("CREATE_AUTHOR not in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR not between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNull() {
            addCriterion("MODIFI_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNotNull() {
            addCriterion("MODIFI_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeEqualTo(Date value) {
            addCriterion("MODIFI_TIME =", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotEqualTo(Date value) {
            addCriterion("MODIFI_TIME <>", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThan(Date value) {
            addCriterion("MODIFI_TIME >", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME >=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThan(Date value) {
            addCriterion("MODIFI_TIME <", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME <=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIn(List<Date> values) {
            addCriterion("MODIFI_TIME in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotIn(List<Date> values) {
            addCriterion("MODIFI_TIME not in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME not between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNull() {
            addCriterion("MODIFI_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNotNull() {
            addCriterion("MODIFI_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR =", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <>", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThan(String value) {
            addCriterion("MODIFI_AUTHOR >", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR >=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThan(String value) {
            addCriterion("MODIFI_AUTHOR <", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLike(String value) {
            addCriterion("MODIFI_AUTHOR like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotLike(String value) {
            addCriterion("MODIFI_AUTHOR not like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR not in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR not between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNull() {
            addCriterion("DATALEVEL is null");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNotNull() {
            addCriterion("DATALEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andDatalevelEqualTo(Integer value) {
            addCriterion("DATALEVEL =", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotEqualTo(Integer value) {
            addCriterion("DATALEVEL <>", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThan(Integer value) {
            addCriterion("DATALEVEL >", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL >=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThan(Integer value) {
            addCriterion("DATALEVEL <", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL <=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelIn(List<Integer> values) {
            addCriterion("DATALEVEL in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotIn(List<Integer> values) {
            addCriterion("DATALEVEL not in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL between", value1, value2, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL not between", value1, value2, "datalevel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 02 16:49:02 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_staff
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}