package com.umbrella.worker.entity;

import java.util.Date;

public class WSupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_ATTAC_ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer wSAttacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_NAME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_CITY
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_DISTRICT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_ADDRESS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_TELEPHONE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_WEBSITE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSWebsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_CONTACT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String wSContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_SECTOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer wSSector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_LICENSE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer wSLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.W_S_GRADE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer wSGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.CREATE_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.CREATE_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String createAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.MODIFI_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Date modifiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.MODIFI_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private String modifiAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.DATALEVEL
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer datalevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_supplier.STATUS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.ID
     *
     * @return the value of w_supplier.ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.ID
     *
     * @param id the value for w_supplier.ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_ATTAC_ID
     *
     * @return the value of w_supplier.W_S_ATTAC_ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getwSAttacId() {
        return wSAttacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_ATTAC_ID
     *
     * @param wSAttacId the value for w_supplier.W_S_ATTAC_ID
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSAttacId(Integer wSAttacId) {
        this.wSAttacId = wSAttacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_NAME
     *
     * @return the value of w_supplier.W_S_NAME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSName() {
        return wSName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_NAME
     *
     * @param wSName the value for w_supplier.W_S_NAME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSName(String wSName) {
        this.wSName = wSName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_CITY
     *
     * @return the value of w_supplier.W_S_CITY
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSCity() {
        return wSCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_CITY
     *
     * @param wSCity the value for w_supplier.W_S_CITY
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSCity(String wSCity) {
        this.wSCity = wSCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_DISTRICT
     *
     * @return the value of w_supplier.W_S_DISTRICT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSDistrict() {
        return wSDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_DISTRICT
     *
     * @param wSDistrict the value for w_supplier.W_S_DISTRICT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSDistrict(String wSDistrict) {
        this.wSDistrict = wSDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_ADDRESS
     *
     * @return the value of w_supplier.W_S_ADDRESS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSAddress() {
        return wSAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_ADDRESS
     *
     * @param wSAddress the value for w_supplier.W_S_ADDRESS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSAddress(String wSAddress) {
        this.wSAddress = wSAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_TELEPHONE
     *
     * @return the value of w_supplier.W_S_TELEPHONE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSTelephone() {
        return wSTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_TELEPHONE
     *
     * @param wSTelephone the value for w_supplier.W_S_TELEPHONE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSTelephone(String wSTelephone) {
        this.wSTelephone = wSTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_WEBSITE
     *
     * @return the value of w_supplier.W_S_WEBSITE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSWebsite() {
        return wSWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_WEBSITE
     *
     * @param wSWebsite the value for w_supplier.W_S_WEBSITE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSWebsite(String wSWebsite) {
        this.wSWebsite = wSWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_CONTACT
     *
     * @return the value of w_supplier.W_S_CONTACT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getwSContact() {
        return wSContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_CONTACT
     *
     * @param wSContact the value for w_supplier.W_S_CONTACT
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSContact(String wSContact) {
        this.wSContact = wSContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_SECTOR
     *
     * @return the value of w_supplier.W_S_SECTOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getwSSector() {
        return wSSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_SECTOR
     *
     * @param wSSector the value for w_supplier.W_S_SECTOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSSector(Integer wSSector) {
        this.wSSector = wSSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_LICENSE
     *
     * @return the value of w_supplier.W_S_LICENSE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getwSLicense() {
        return wSLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_LICENSE
     *
     * @param wSLicense the value for w_supplier.W_S_LICENSE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSLicense(Integer wSLicense) {
        this.wSLicense = wSLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.W_S_GRADE
     *
     * @return the value of w_supplier.W_S_GRADE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getwSGrade() {
        return wSGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.W_S_GRADE
     *
     * @param wSGrade the value for w_supplier.W_S_GRADE
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setwSGrade(Integer wSGrade) {
        this.wSGrade = wSGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.CREATE_TIME
     *
     * @return the value of w_supplier.CREATE_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.CREATE_TIME
     *
     * @param createTime the value for w_supplier.CREATE_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.CREATE_AUTHOR
     *
     * @return the value of w_supplier.CREATE_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.CREATE_AUTHOR
     *
     * @param createAuthor the value for w_supplier.CREATE_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.MODIFI_TIME
     *
     * @return the value of w_supplier.MODIFI_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Date getModifiTime() {
        return modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.MODIFI_TIME
     *
     * @param modifiTime the value for w_supplier.MODIFI_TIME
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setModifiTime(Date modifiTime) {
        this.modifiTime = modifiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.MODIFI_AUTHOR
     *
     * @return the value of w_supplier.MODIFI_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getModifiAuthor() {
        return modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.MODIFI_AUTHOR
     *
     * @param modifiAuthor the value for w_supplier.MODIFI_AUTHOR
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setModifiAuthor(String modifiAuthor) {
        this.modifiAuthor = modifiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.DATALEVEL
     *
     * @return the value of w_supplier.DATALEVEL
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getDatalevel() {
        return datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.DATALEVEL
     *
     * @param datalevel the value for w_supplier.DATALEVEL
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setDatalevel(Integer datalevel) {
        this.datalevel = datalevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_supplier.STATUS
     *
     * @return the value of w_supplier.STATUS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_supplier.STATUS
     *
     * @param status the value for w_supplier.STATUS
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}