package com.umbrella.worker.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WSupplierExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected boolean distinct;
    
    protected String pageByClause;

    public String getPageByClause() {
		return pageByClause;
	}

	public void setPageByClause(String pageByClause) {
		this.pageByClause = pageByClause;
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public WSupplierExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIsNull() {
            addCriterion("W_S_ATTAC_ID is null");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIsNotNull() {
            addCriterion("W_S_ATTAC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID =", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID <>", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdGreaterThan(Integer value) {
            addCriterion("W_S_ATTAC_ID >", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID >=", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdLessThan(Integer value) {
            addCriterion("W_S_ATTAC_ID <", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_ATTAC_ID <=", value, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdIn(List<Integer> values) {
            addCriterion("W_S_ATTAC_ID in", values, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotIn(List<Integer> values) {
            addCriterion("W_S_ATTAC_ID not in", values, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdBetween(Integer value1, Integer value2) {
            addCriterion("W_S_ATTAC_ID between", value1, value2, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSAttacIdNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_ATTAC_ID not between", value1, value2, "wSAttacId");
            return (Criteria) this;
        }

        public Criteria andWSNameIsNull() {
            addCriterion("W_S_NAME is null");
            return (Criteria) this;
        }

        public Criteria andWSNameIsNotNull() {
            addCriterion("W_S_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andWSNameEqualTo(String value) {
            addCriterion("W_S_NAME =", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameNotEqualTo(String value) {
            addCriterion("W_S_NAME <>", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameGreaterThan(String value) {
            addCriterion("W_S_NAME >", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_NAME >=", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameLessThan(String value) {
            addCriterion("W_S_NAME <", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameLessThanOrEqualTo(String value) {
            addCriterion("W_S_NAME <=", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameLike(String value) {
            addCriterion("W_S_NAME like", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameNotLike(String value) {
            addCriterion("W_S_NAME not like", value, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameIn(List<String> values) {
            addCriterion("W_S_NAME in", values, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameNotIn(List<String> values) {
            addCriterion("W_S_NAME not in", values, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameBetween(String value1, String value2) {
            addCriterion("W_S_NAME between", value1, value2, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSNameNotBetween(String value1, String value2) {
            addCriterion("W_S_NAME not between", value1, value2, "wSName");
            return (Criteria) this;
        }

        public Criteria andWSCityIsNull() {
            addCriterion("W_S_CITY is null");
            return (Criteria) this;
        }

        public Criteria andWSCityIsNotNull() {
            addCriterion("W_S_CITY is not null");
            return (Criteria) this;
        }

        public Criteria andWSCityEqualTo(String value) {
            addCriterion("W_S_CITY =", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityNotEqualTo(String value) {
            addCriterion("W_S_CITY <>", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityGreaterThan(String value) {
            addCriterion("W_S_CITY >", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_CITY >=", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityLessThan(String value) {
            addCriterion("W_S_CITY <", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityLessThanOrEqualTo(String value) {
            addCriterion("W_S_CITY <=", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityLike(String value) {
            addCriterion("W_S_CITY like", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityNotLike(String value) {
            addCriterion("W_S_CITY not like", value, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityIn(List<String> values) {
            addCriterion("W_S_CITY in", values, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityNotIn(List<String> values) {
            addCriterion("W_S_CITY not in", values, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityBetween(String value1, String value2) {
            addCriterion("W_S_CITY between", value1, value2, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSCityNotBetween(String value1, String value2) {
            addCriterion("W_S_CITY not between", value1, value2, "wSCity");
            return (Criteria) this;
        }

        public Criteria andWSDistrictIsNull() {
            addCriterion("W_S_DISTRICT is null");
            return (Criteria) this;
        }

        public Criteria andWSDistrictIsNotNull() {
            addCriterion("W_S_DISTRICT is not null");
            return (Criteria) this;
        }

        public Criteria andWSDistrictEqualTo(String value) {
            addCriterion("W_S_DISTRICT =", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictNotEqualTo(String value) {
            addCriterion("W_S_DISTRICT <>", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictGreaterThan(String value) {
            addCriterion("W_S_DISTRICT >", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_DISTRICT >=", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictLessThan(String value) {
            addCriterion("W_S_DISTRICT <", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictLessThanOrEqualTo(String value) {
            addCriterion("W_S_DISTRICT <=", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictLike(String value) {
            addCriterion("W_S_DISTRICT like", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictNotLike(String value) {
            addCriterion("W_S_DISTRICT not like", value, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictIn(List<String> values) {
            addCriterion("W_S_DISTRICT in", values, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictNotIn(List<String> values) {
            addCriterion("W_S_DISTRICT not in", values, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictBetween(String value1, String value2) {
            addCriterion("W_S_DISTRICT between", value1, value2, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSDistrictNotBetween(String value1, String value2) {
            addCriterion("W_S_DISTRICT not between", value1, value2, "wSDistrict");
            return (Criteria) this;
        }

        public Criteria andWSAddressIsNull() {
            addCriterion("W_S_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andWSAddressIsNotNull() {
            addCriterion("W_S_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andWSAddressEqualTo(String value) {
            addCriterion("W_S_ADDRESS =", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotEqualTo(String value) {
            addCriterion("W_S_ADDRESS <>", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressGreaterThan(String value) {
            addCriterion("W_S_ADDRESS >", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_ADDRESS >=", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLessThan(String value) {
            addCriterion("W_S_ADDRESS <", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLessThanOrEqualTo(String value) {
            addCriterion("W_S_ADDRESS <=", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressLike(String value) {
            addCriterion("W_S_ADDRESS like", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotLike(String value) {
            addCriterion("W_S_ADDRESS not like", value, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressIn(List<String> values) {
            addCriterion("W_S_ADDRESS in", values, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotIn(List<String> values) {
            addCriterion("W_S_ADDRESS not in", values, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressBetween(String value1, String value2) {
            addCriterion("W_S_ADDRESS between", value1, value2, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSAddressNotBetween(String value1, String value2) {
            addCriterion("W_S_ADDRESS not between", value1, value2, "wSAddress");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIsNull() {
            addCriterion("W_S_TELEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIsNotNull() {
            addCriterion("W_S_TELEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneEqualTo(String value) {
            addCriterion("W_S_TELEPHONE =", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotEqualTo(String value) {
            addCriterion("W_S_TELEPHONE <>", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneGreaterThan(String value) {
            addCriterion("W_S_TELEPHONE >", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_TELEPHONE >=", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLessThan(String value) {
            addCriterion("W_S_TELEPHONE <", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLessThanOrEqualTo(String value) {
            addCriterion("W_S_TELEPHONE <=", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneLike(String value) {
            addCriterion("W_S_TELEPHONE like", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotLike(String value) {
            addCriterion("W_S_TELEPHONE not like", value, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneIn(List<String> values) {
            addCriterion("W_S_TELEPHONE in", values, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotIn(List<String> values) {
            addCriterion("W_S_TELEPHONE not in", values, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneBetween(String value1, String value2) {
            addCriterion("W_S_TELEPHONE between", value1, value2, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSTelephoneNotBetween(String value1, String value2) {
            addCriterion("W_S_TELEPHONE not between", value1, value2, "wSTelephone");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteIsNull() {
            addCriterion("W_S_WEBSITE is null");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteIsNotNull() {
            addCriterion("W_S_WEBSITE is not null");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteEqualTo(String value) {
            addCriterion("W_S_WEBSITE =", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteNotEqualTo(String value) {
            addCriterion("W_S_WEBSITE <>", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteGreaterThan(String value) {
            addCriterion("W_S_WEBSITE >", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_WEBSITE >=", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteLessThan(String value) {
            addCriterion("W_S_WEBSITE <", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteLessThanOrEqualTo(String value) {
            addCriterion("W_S_WEBSITE <=", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteLike(String value) {
            addCriterion("W_S_WEBSITE like", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteNotLike(String value) {
            addCriterion("W_S_WEBSITE not like", value, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteIn(List<String> values) {
            addCriterion("W_S_WEBSITE in", values, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteNotIn(List<String> values) {
            addCriterion("W_S_WEBSITE not in", values, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteBetween(String value1, String value2) {
            addCriterion("W_S_WEBSITE between", value1, value2, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSWebsiteNotBetween(String value1, String value2) {
            addCriterion("W_S_WEBSITE not between", value1, value2, "wSWebsite");
            return (Criteria) this;
        }

        public Criteria andWSContactIsNull() {
            addCriterion("W_S_CONTACT is null");
            return (Criteria) this;
        }

        public Criteria andWSContactIsNotNull() {
            addCriterion("W_S_CONTACT is not null");
            return (Criteria) this;
        }

        public Criteria andWSContactEqualTo(String value) {
            addCriterion("W_S_CONTACT =", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactNotEqualTo(String value) {
            addCriterion("W_S_CONTACT <>", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactGreaterThan(String value) {
            addCriterion("W_S_CONTACT >", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactGreaterThanOrEqualTo(String value) {
            addCriterion("W_S_CONTACT >=", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactLessThan(String value) {
            addCriterion("W_S_CONTACT <", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactLessThanOrEqualTo(String value) {
            addCriterion("W_S_CONTACT <=", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactLike(String value) {
            addCriterion("W_S_CONTACT like", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactNotLike(String value) {
            addCriterion("W_S_CONTACT not like", value, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactIn(List<String> values) {
            addCriterion("W_S_CONTACT in", values, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactNotIn(List<String> values) {
            addCriterion("W_S_CONTACT not in", values, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactBetween(String value1, String value2) {
            addCriterion("W_S_CONTACT between", value1, value2, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSContactNotBetween(String value1, String value2) {
            addCriterion("W_S_CONTACT not between", value1, value2, "wSContact");
            return (Criteria) this;
        }

        public Criteria andWSSectorIsNull() {
            addCriterion("W_S_SECTOR is null");
            return (Criteria) this;
        }

        public Criteria andWSSectorIsNotNull() {
            addCriterion("W_S_SECTOR is not null");
            return (Criteria) this;
        }

        public Criteria andWSSectorEqualTo(Integer value) {
            addCriterion("W_S_SECTOR =", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorNotEqualTo(Integer value) {
            addCriterion("W_S_SECTOR <>", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorGreaterThan(Integer value) {
            addCriterion("W_S_SECTOR >", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_SECTOR >=", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorLessThan(Integer value) {
            addCriterion("W_S_SECTOR <", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_SECTOR <=", value, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorIn(List<Integer> values) {
            addCriterion("W_S_SECTOR in", values, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorNotIn(List<Integer> values) {
            addCriterion("W_S_SECTOR not in", values, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SECTOR between", value1, value2, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSSectorNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_SECTOR not between", value1, value2, "wSSector");
            return (Criteria) this;
        }

        public Criteria andWSLicenseIsNull() {
            addCriterion("W_S_LICENSE is null");
            return (Criteria) this;
        }

        public Criteria andWSLicenseIsNotNull() {
            addCriterion("W_S_LICENSE is not null");
            return (Criteria) this;
        }

        public Criteria andWSLicenseEqualTo(Integer value) {
            addCriterion("W_S_LICENSE =", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseNotEqualTo(Integer value) {
            addCriterion("W_S_LICENSE <>", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseGreaterThan(Integer value) {
            addCriterion("W_S_LICENSE >", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_LICENSE >=", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseLessThan(Integer value) {
            addCriterion("W_S_LICENSE <", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_LICENSE <=", value, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseIn(List<Integer> values) {
            addCriterion("W_S_LICENSE in", values, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseNotIn(List<Integer> values) {
            addCriterion("W_S_LICENSE not in", values, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseBetween(Integer value1, Integer value2) {
            addCriterion("W_S_LICENSE between", value1, value2, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSLicenseNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_LICENSE not between", value1, value2, "wSLicense");
            return (Criteria) this;
        }

        public Criteria andWSGradeIsNull() {
            addCriterion("W_S_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andWSGradeIsNotNull() {
            addCriterion("W_S_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andWSGradeEqualTo(Integer value) {
            addCriterion("W_S_GRADE =", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotEqualTo(Integer value) {
            addCriterion("W_S_GRADE <>", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeGreaterThan(Integer value) {
            addCriterion("W_S_GRADE >", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("W_S_GRADE >=", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeLessThan(Integer value) {
            addCriterion("W_S_GRADE <", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeLessThanOrEqualTo(Integer value) {
            addCriterion("W_S_GRADE <=", value, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeIn(List<Integer> values) {
            addCriterion("W_S_GRADE in", values, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotIn(List<Integer> values) {
            addCriterion("W_S_GRADE not in", values, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeBetween(Integer value1, Integer value2) {
            addCriterion("W_S_GRADE between", value1, value2, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andWSGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("W_S_GRADE not between", value1, value2, "wSGrade");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNull() {
            addCriterion("CREATE_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIsNotNull() {
            addCriterion("CREATE_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorEqualTo(String value) {
            addCriterion("CREATE_AUTHOR =", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <>", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThan(String value) {
            addCriterion("CREATE_AUTHOR >", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR >=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThan(String value) {
            addCriterion("CREATE_AUTHOR <", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLessThanOrEqualTo(String value) {
            addCriterion("CREATE_AUTHOR <=", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorLike(String value) {
            addCriterion("CREATE_AUTHOR like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotLike(String value) {
            addCriterion("CREATE_AUTHOR not like", value, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorIn(List<String> values) {
            addCriterion("CREATE_AUTHOR in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotIn(List<String> values) {
            addCriterion("CREATE_AUTHOR not in", values, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andCreateAuthorNotBetween(String value1, String value2) {
            addCriterion("CREATE_AUTHOR not between", value1, value2, "createAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNull() {
            addCriterion("MODIFI_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIsNotNull() {
            addCriterion("MODIFI_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifiTimeEqualTo(Date value) {
            addCriterion("MODIFI_TIME =", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotEqualTo(Date value) {
            addCriterion("MODIFI_TIME <>", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThan(Date value) {
            addCriterion("MODIFI_TIME >", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME >=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThan(Date value) {
            addCriterion("MODIFI_TIME <", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFI_TIME <=", value, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeIn(List<Date> values) {
            addCriterion("MODIFI_TIME in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotIn(List<Date> values) {
            addCriterion("MODIFI_TIME not in", values, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFI_TIME not between", value1, value2, "modifiTime");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNull() {
            addCriterion("MODIFI_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIsNotNull() {
            addCriterion("MODIFI_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR =", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <>", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThan(String value) {
            addCriterion("MODIFI_AUTHOR >", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR >=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThan(String value) {
            addCriterion("MODIFI_AUTHOR <", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLessThanOrEqualTo(String value) {
            addCriterion("MODIFI_AUTHOR <=", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorLike(String value) {
            addCriterion("MODIFI_AUTHOR like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotLike(String value) {
            addCriterion("MODIFI_AUTHOR not like", value, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotIn(List<String> values) {
            addCriterion("MODIFI_AUTHOR not in", values, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andModifiAuthorNotBetween(String value1, String value2) {
            addCriterion("MODIFI_AUTHOR not between", value1, value2, "modifiAuthor");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNull() {
            addCriterion("DATALEVEL is null");
            return (Criteria) this;
        }

        public Criteria andDatalevelIsNotNull() {
            addCriterion("DATALEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andDatalevelEqualTo(Integer value) {
            addCriterion("DATALEVEL =", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotEqualTo(Integer value) {
            addCriterion("DATALEVEL <>", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThan(Integer value) {
            addCriterion("DATALEVEL >", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL >=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThan(Integer value) {
            addCriterion("DATALEVEL <", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelLessThanOrEqualTo(Integer value) {
            addCriterion("DATALEVEL <=", value, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelIn(List<Integer> values) {
            addCriterion("DATALEVEL in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotIn(List<Integer> values) {
            addCriterion("DATALEVEL not in", values, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL between", value1, value2, "datalevel");
            return (Criteria) this;
        }

        public Criteria andDatalevelNotBetween(Integer value1, Integer value2) {
            addCriterion("DATALEVEL not between", value1, value2, "datalevel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_supplier
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 02 16:49:02 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_supplier
     *
     * @mbggenerated Tue Aug 02 16:49:02 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}